import os
import random
import sys


def print_help():
    print('A simple Python script to modify a ciphertext. For every single byte of the ciphertext there is a 33% '
          'chance\n'
          'that it will be modified. The modification is performed as the XOR product of a given byte and a randomly '
          'generated byte.\n'
          'To use this program, specify the path to the ciphertext as the first argument.\n'
          f'Example: python3 {os.path.basename(sys.argv[0])} /your/desired/location/for/ciphertext.txt\n')


def main():
    if len(sys.argv) < 2:
        print('Please specify ciphertext path!')
        return

    if sys.argv[1] == 'help':
        print_help()
        return

    path = sys.argv[1]
    output_extension = os.path.splitext(path)[1]
    print(os.path.splitext(path))
    with open(path, 'rb') as ciphertext, \
            open(os.path.dirname(path) + "/new_ciphertext" + output_extension, 'wb') as new_ciphertext:
        ciphertext = ciphertext.read()
        print('Old ciphertext:', ciphertext, len(ciphertext))
        new_ciphertext_bytes = []
        for byte in ciphertext:
            if random.random() < 0.3:
                byte = byte ^ int.from_bytes(os.urandom(1), 'big')
            new_ciphertext_bytes.append(byte)
        new_ciphertext_bytes = bytes(new_ciphertext_bytes)
        print('New ciphertext', new_ciphertext_bytes, len(ciphertext))
        new_ciphertext.write(new_ciphertext_bytes)


if __name__ == '__main__':
    main()
